export const mockData = {
  restaurant: {
    name: "La Cocina Dorada",
    slogan: "Sabores auténticos que despiertan tus sentidos",
    image: "/placeholder.svg?height=800&width=1200",
  },

  categories: [
    { id: "desayunos", name: "Desayunos", icon: "🍳" },
    { id: "comida-rapida", name: "Comida Rápida", icon: "🍔" },
    { id: "platos-principales", name: "Platos Principales", icon: "🍽️" },
    { id: "postres", name: "Postres", icon: "🍰" },
    { id: "bebidas", name: "Bebidas", icon: "🥤" },
    { id: "ensaladas", name: "Ensaladas", icon: "🥗" },
  ],

  categoriaIds: [
    {
      id: "1",
      name: "Desayuno Completo",
      description:
        "Huevos revueltos, tocino crujiente, tostadas artesanales y café recién molido. El desayuno perfecto para empezar el día con energía.",
      price: 12.99,
      image: "/placeholder.svg?height=300&width=400",
      ingredients: ["Huevos frescos", "Tocino", "Pan artesanal", "Mantequilla", "Café"],
      category: "desayunos",
      available: true,
    },
    {
      id: "2",
      name: "Hamburguesa Clásica",
      description:
        "Carne de res jugosa, lechuga fresca, tomate, cebolla y nuestra salsa especial en pan brioche tostado.",
      price: 15.5,
      image: "/placeholder.svg?height=300&width=400",
      ingredients: ["Carne de res", "Pan brioche", "Lechuga", "Tomate", "Cebolla", "Salsa especial"],
      category: "comida-rapida",
      available: true,
    },
    {
      id: "3",
      name: "Salmón a la Parrilla",
      description: "Filete de salmón fresco a la parrilla con vegetales de temporada y salsa de limón y hierbas.",
      price: 24.99,
      image: "/placeholder.svg?height=300&width=400",
      ingredients: ["Salmón fresco", "Vegetales de temporada", "Limón", "Hierbas frescas", "Aceite de oliva"],
      category: "platos-principales",
      available: true,
    },
    {
      id: "4",
      name: "Tiramisú Casero",
      description: "El clásico postre italiano preparado con mascarpone, café espresso y cacao en polvo.",
      price: 8.99,
      image: "/placeholder.svg?height=300&width=400",
      ingredients: ["Mascarpone", "Café espresso", "Bizcochos", "Cacao", "Huevos"],
      category: "postres",
      available: true,
    },
    {
      id: "5",
      name: "Smoothie Tropical",
      description:
        "Refrescante mezcla de mango, piña, plátano y leche de coco. Perfecto para cualquier momento del día.",
      price: 6.5,
      image: "/placeholder.svg?height=300&width=400",
      ingredients: ["Mango", "Piña", "Plátano", "Leche de coco", "Hielo"],
      category: "bebidas",
      available: true,
    },
    {
      id: "6",
      name: "Ensalada César",
      description: "Lechuga romana fresca, crutones caseros, queso parmesano y nuestra auténtica salsa César.",
      price: 11.99,
      image: "/placeholder.svg?height=300&width=400",
      ingredients: ["Lechuga romana", "Crutones", "Queso parmesano", "Salsa César", "Anchoas"],
      category: "ensaladas",
      available: true,
    },
    {
      id: "7",
      name: "Pancakes con Miel",
      description: "Esponjosos pancakes servidos con miel de maple auténtica, mantequilla y frutas frescas.",
      price: 9.99,
      image: "/placeholder.svg?height=300&width=400",
      ingredients: ["Harina", "Huevos", "Leche", "Miel de maple", "Frutas frescas", "Mantequilla"],
      category: "desayunos",
      available: true,
    },
    {
      id: "8",
      name: "Pizza Margherita",
      description: "Pizza tradicional italiana con salsa de tomate, mozzarella fresca y albahaca sobre masa artesanal.",
      price: 18.5,
      image: "/placeholder.svg?height=300&width=400",
      ingredients: ["Masa artesanal", "Salsa de tomate", "Mozzarella", "Albahaca", "Aceite de oliva"],
      category: "platos-principales",
      available: true,
    },
    {
      id: "9",
      name: "Cheesecake de Frutos Rojos",
      description: "Cremoso cheesecake con base de galleta y cobertura de frutos rojos de temporada.",
      price: 10.5,
      image: "/placeholder.svg?height=300&width=400",
      ingredients: ["Queso crema", "Galletas", "Frutos rojos", "Azúcar", "Vainilla"],
      category: "postres",
      available: false,
    },
    {
      id: "10",
      name: "Café Americano",
      description: "Café espresso doble diluido con agua caliente. Servido en taza de cerámica artesanal.",
      price: 3.5,
      image: "/placeholder.svg?height=300&width=400",
      ingredients: ["Café espresso", "Agua caliente"],
      category: "bebidas",
      available: true,
    },
    {
      id: "11",
      name: "Ensalada Mediterránea",
      description: "Mezcla de vegetales frescos, aceitunas, queso feta y aderezo de aceite de oliva y limón.",
      price: 13.99,
      image: "/placeholder.svg?height=300&width=400",
      ingredients: ["Tomate", "Pepino", "Aceitunas", "Queso feta", "Cebolla roja", "Aceite de oliva"],
      category: "ensaladas",
      available: true,
    },
    {
      id: "12",
      name: "Tacos de Pollo",
      description: "Tres tacos suaves con pollo marinado, pico de gallo, aguacate y salsa verde picante.",
      price: 14.99,
      image: "/placeholder.svg?height=300&width=400",
      ingredients: ["Tortillas", "Pollo marinado", "Aguacate", "Tomate", "Cebolla", "Cilantro", "Salsa verde"],
      category: "comida-rapida",
      available: true,
    },
  ],
}
